### ISSUE TITLE
publish on maven central

### ISSUE THREAD

**Issue by MasseGuillaume** [okta/oktasdk-java#1]
can you publish an artifact on [maven central](http://search.maven.org/#search%7Cga%7C1%7Cg%3A%22com.okta%22) ?

**Comment by thomasvandoren** [comment]
:+1:

**Comment by chrisdostert** [comment]
+1

**Comment by sittiwet** [comment]
+1

**Comment by enriquezrene** [comment]
+1

**Comment by gantzm** [comment]
+1

**Comment by sunieldalal** [comment]
+1

**Comment by nisbshah** [comment]
+1

**Comment by braghome** [comment]
👍

**Comment by jpf** [comment]
Thanks for the +1 and 👍 everybody! We're looking into getting our SDK into Maven and will update everybody here once that's been done.

**Comment by sleroy** [comment]
I deployed it on bintray with https://github.com/sleroy/oktasdk-java

**Comment by rchild-okta** [comment]
We published a version of the SDK late last year:
https://search.maven.org/#search%7Cga%7C1%7Ca%3A%22okta-sdk%22

I'll leave this bug open for the work we're doing now to publish the latest version to Maven ( @lboyette-okta )

**Comment by samuelneff** [comment]
+1 for keeping up to date

**Comment by johngronberg-okta** [comment]
We're working away on the newest version of the Java SDK, and will be pushing a new version to maven in the future. Closing this as it is in our development pipeline.

**Comment by samuelneff** [comment]
Thank you

**Comment by sleroy** [comment]
If you need any help, pleae let me know :-)
