### ISSUE TITLE
README.md wrong

### ISSUE THREAD

**Issue by roadmixer88** [okta/oktasdk-java#20]
When adding the Advanced Search methods to the UserApiClient, the methods documented are wrong
it mentions client.getUsersWithSearch, when what was written is client.getUsersWithAdvancedSearch

I also feel this feature is significant enough that the pom.xml should be reved to reflect the difference on compile.

**Comment by lboyette-okta** [comment]
Thanks for your feedback! The docs have been updated. The pom has also been updated since this change.
