### ISSUE TITLE
Adding user to application.

### ISSUE THREAD

**Issue by gantzm** [okta/oktasdk-java#22]
Is it possible to add an existing user to an existing application?  I can get the user and application from the SDK, but I don't see a way to link them.

**Comment by msamm-r7** [comment]
i'm currently doing this as part of some work i'm undertaking. i've cloned and branched.

**Comment by rmanga7** [comment]
Hi,
is this feature has been implemented ?

Thanks

**Comment by jmelberg-okta** [comment]
@gantzm: This is possible using the `AppUserApiClient` class. For example,

```java
import com.okta.sdk.framework.ApiClientConfiguration;
import com.okta.sdk.models.apps.AppUser;
import com.okta.sdk.clients.AppUserApiClient;


ApiClientConfiguration oktaSettings = new ApiClientConfiguration(
                "https://example.okta.com",
                "API_KEY");

AppUserApiClient appUserApiClient = new AppUserApiClient(oktaSettings);

// Assign user by ID to app by ID
AppUser appUser = appUserApiClient.createAppUser("appId", "userId");
```

**Comment by RvPr** [comment]
Hi. I see that the AppUserApiClient class has been deleted some time between Jan 31 and today. Could you please reopen this issue, and clarify if this feature will be implemented in the SDK, at some point in the coming month?

**Comment by johnbhurst** [comment]
Seems that this issue still exists as of 1.3.0 (October 2018). 

I cannot find a way to assign a user to an application using the Java API. 

Any update?

**Comment by bdemers** [comment]
It should be:

```java
 client.getApplication("your-app-id").assignUserToApplication(appUser)
```

Here is an example in a test (groovy)
https://github.com/okta/okta-sdk-java/blob/master/integration-tests/src/test/groovy/com/okta/sdk/tests/it/ApplicationsIT.groovy#L484-L491

**Comment by johnbhurst** [comment]
Thanks so much!

I was trying to do something like that, but could not figure out how to create a new AppUser. Being new to the API, I missed the client.instantiate() method.

Now that I looked again, there are plenty of examples of that on the GitHub main page.

**Comment by bdemers** [comment]
@johnbhurst thanks for the follow up!
