### ISSUE TITLE
Is it possible to get the custom profile attribute?

### ISSUE THREAD

**Issue by naveenann** [okta/oktasdk-java#26]
I would like to get the custom user profile attribute  described here http://developer.okta.com/docs/api/resources/users.html#custom-profile-properties. Is there any way to get it using the API?

**Comment by jmelberg-okta** [comment]
Custom/unmapped properties are available under the `UserProfile` class. Call the `getUnmapped()` method to retrieve fields returned through the API:

```java
UserApiClient usersClient = new UserApiClient( /* oktaSettings */);
User user = userApiClient.getUser("ID/loginName/loginShortName");
// users.getProfile().getUnmapped());
```
