### ISSUE TITLE
static AuthResult Status

### ISSUE THREAD

**Issue by harel-e** [okta/oktasdk-java#27]
Hello,

It will be easier to check for Auth status result if the either the status is enum or static
In other words, convert AuthResult.Status to enum or have the fields of AuthResult.Status be final static  

So we can write  'AuthResult.Status.SUCCESS' instead of   'new AuthResult.Status().SUCCESS'

**Comment by jmelberg-okta** [comment]
To keep with the coding conventions throughout this SDK, it is best practice to check the Auth status with the `getStatus()` method. For example:
```java
AuthApiClient authClient = new AuthApiClient(oktaSettings);

// Check if the user credentials are valid
AuthResult result = authClient.authenticate(username, password, someRelayState);

// Verify SUCCESS status
if (result.getStatus().equals("SUCCESS")) { /* Do something */ }
```
