### ISSUE TITLE
forgetPassword method does not send recovery emails

### ISSUE THREAD

**Issue by jennifergarcia** [okta/oktasdk-java#30]
The forgetPassword method in AuthApiClient does not send recovery emails, like it should. 
Because of this, we cannot get the recovery token necessary for the user to perform the rest of the password reset.

The root cause is that the method is not setting the factorType, like the API call does:
"factorType": "EMAIL"

**Comment by jpf** [comment]
Thanks for the details and PR @jennifergarcia! I've opened a ticket (OKTA-106319) for this issue with the team that maintains this code.

**Comment by jennifergarcia** [comment]
This was commited under https://github.com/okta/oktasdk-java/commit/f265d03f6bc78ea365a2f3b025c526d7616fe082
