### ISSUE TITLE
Release date for create user within a group branch?

### ISSUE THREAD

**Issue by samuelneff** [okta/oktasdk-java#46]
We're really happy to see an active branch with the ability to create a user within a group. Is there an expected release date of an updated SDK with this functionality?

Thanks,

Sam

**Comment by jmelberg-okta** [comment]
@samuelneff: This feature has been [merged (#28)](https://github.com/okta/oktasdk-java/pull/28). Let us know if you would like to see any other improvements!

**Comment by samuelneff** [comment]
Thanks for the update. We'll grab the latest.
