### ISSUE TITLE
Allow customer auth header in Okta Java SDK

### ISSUE THREAD

**Issue by peggyxue-okta** [okta/oktasdk-java#48]
Okta SDK should make the Authorization header more flexible if user provide then allow them user their or use the default(what Okta needs) so user don’t provide our own. The reason behind that is some users environment has additional API gateway they need to authentication against, in this case, the auth header looks like below:

Accept: application/json
Content-Type: application/json
OKTAAuthorization: SSWS {{apikey}}
Authorization: Basic {{SuperPowerBasicAuthKey}}

I have reported this enhancement to our engineer team internal

**Comment by jmelberg-okta** [comment]
Fixed with enhancement [(#53)](https://github.com/okta/oktasdk-java/pull/53)
