### ISSUE TITLE
Setting Attribute Values?

### ISSUE THREAD

**Issue by basement199** [okta/oktasdk-java#49]
Hi,

I need to create some users and I need to populate profile attributes other than the standard (firstname,lastname,email,login).  Is it possible to do this withe API?

For example I need to populate the employeeNumber attribute.

thanks,
Freeman

**Comment by zauberjoe** [comment]
Hello Freeman,

I have managed this in the past using the following code:

` private User createUserFromEmployee(Employee employee) {
        User user = new User();
        UserProfile userProfile = new UserProfile();
        userProfile.setEmail(employee.getEmailAddress());
        userProfile.setFirstName(employee.getFirstName());
        userProfile.setLastName(employee.getLastName());
        userProfile.setLogin(employee.getEmailAddress());
        Map<String,Object> unmapped = userProfile.getUnmapped();
        unmapped.put("employeeNumber", employee.getEmployeeNumber());
        user.setProfile(userProfile);
        return user;
    }`

Hope this helps,

Joe

**Comment by basement199** [comment]
Hi Joe,

That worked!   Appreciate the tip.

thanks,
Freeman
