### ISSUE TITLE
Version number in POM never updated?

### ISSUE THREAD

**Issue by samuelneff** [okta/oktasdk-java#51]
I noticed that releases are provided through GitHub but they all have the same 0.0.4-SNAPSHOT version number in the pom.xml.

Would it be possible to set a release number in the pom and update it whenever there is an official release?

Thanks,

Sam

**Comment by jmelberg-okta** [comment]
@samuelneff: Great recommendation. We will be releasing a 1.0.0 version to maven in the coming weeks. Updates will be mirrored with their respective release versions once published.

**Comment by karianna** [comment]
@jmelberg-okta Hi there - we've been unable to find the 1.0.0 release.  Is it in Maven Central somewhere under a different group Id?

**Comment by bdemers** [comment]
The current release is` 0.0.4` and the next release will be `0.5.0` (this is a complete re-write) and we will be using this to move forward to a `1.0.0` see the `new-deal` branch if interested (NOTE: if this branch no longer exists it will have already been merged to master)

**Comment by karianna** [comment]
@bdemers Thanks for the update.  Will there be some RC's coming out soon, we've coded against the 0.0.4 API but are concerned that if it radically changes then we'll run out of time to migrate..

**Comment by bdemers** [comment]
@karianna should be the end of week for the release.

If you are currently using 0.0.4, you will still be able to use it.  We likely, will only be making bug/security fixes to that version though.

I'll likely be moving the branches over later today or tomorrow.  At that point I will make sure the pom versions are set correctly (so they do NOT conflict with any released versions)
